# **Project 1**

## 1.1 Bisection Method


In [ ]:
def root(g, e, a, b, i):
#g is the function, e is epsilon, a-b is the interval, i is the beginning number of iterations (0)
  i = i+1
  c = (a+b)/2
  if (g(a))*(g(b)) > 0:
    #both ends of the interval have the same sign
    print("There is no gaurantee there is a root in this interval")
  elif g(a) == 0:
    print(i)
    return a
  elif g(b) == 0:
    print(i)
    return b
  elif g(c) == 0:
    print(i)
    return c
  elif (g(a))*(g(c)) < 0:
    if abs(g(c)) < e:
      print(i)
      return c
    else:
      return root(g, e, a, c,i)
  elif (g(c))*(g(b)) < 0:
    if abs(g(c)) < e:
      print(i)
      return c
    else:
      return root(g, e, c, b,i)


In [ ]:
import math
def function(x):
  return math.e**(x**2)

def derivative(x):
  return 2*x*math.e**(x**2)

def second_derivative(x):
  return 4*(pow(x,2))*(pow(math.e,(pow(x,2)))) + 2*(pow(math.e,(pow(x,2))))


In [ ]:
def bruteForce(a,b,deriv,tol, numit):
#numit is the number of points checked on the first iteration and is doubled after each iteratio
  intervalSize = (b-a)/(numit-1)
  for i in range(numit):
    if deriv(a+i*intervalSize) < tol and deriv(a+i*intervalSize) > -1*tol :
      print(math.log(numit, 2))
      return a+i*intervalSize
  numit *= 2
  return bruteForce(a,b,deriv,tol,numit)

In [ ]:
def brute_Force(a,b,deriv,tol, numit, iter):
#numit is the number of points checked on the first iteration and is doubled after each iteratio
  intervalSize = (b-a)/(numit-1)
  for i in range(numit):
    iter += 1
    if abs(deriv(a+i*intervalSize)) < tol:
      print(iter)
      return a+i*intervalSize
    
  numit *= 2
  return brute_Force(a,b,deriv,tol,numit, iter)

Based on this data the bisection method is easily the more efficient function, the highest number of iterations it took was 10, versus the brute force method, when faced with the same tolerance and interval size took thousands of iterations. 

# 1.2 Gradient Descent

## 1.2.1

In [ ]:
def gradient_descent(f, deriv_f, x0, tol, L, it):
  it += 1
  alpha = 1/L
  x_k1 = x0 - alpha * deriv_f(x0)
  
  
  if abs(deriv_f(x_k1)) < tol :
    print("The number of iterations is: " + str(it))
    return x_k1
    
  return  gradient_descent(f, deriv_f, x_k1, tol, L, it)

## 1.2.2

In [ ]:
gradient_descent(function, derivative, -0.5, 0.0005, 4, 0)

The number of iterations is: 11


-0.00016742218381190065

In [ ]:
gradient_descent(function, derivative, -1, 0.0005, 4, 0)


The number of iterations is: 12


0.00014642970147504768

## 1.2.3

In [ ]:
def dynamic_gradient_descent(deriv_f, x0, tol, alpha, it):
  it += 1
  x_k1 = x0 - alpha * deriv_f(x0)
  if(abs(deriv_f(x_k1)) < tol):
    print(it)
    return x_k1
  alpha = ((x_k1 - x0)*(deriv_f(x_k1) - deriv_f(x0)))/(deriv_f(x_k1) - deriv_f(x0))**2
  return  dynamic_gradient_descent(deriv_f, x_k1, tol, alpha, it)

## 1.2.4

In [ ]:
dynamic_gradient_descent(derivative, 0.0005, 0.0005, 1/4, 0)

1


0.0002499999374999922

In [ ]:
dynamic_gradient_descent(derivative, -0.5, 0.0005, 1/4, 0)

4


-4.931233889874601e-06

In [ ]:
dynamic_gradient_descent(derivative, -1, 0.0005, 1/4, 0)

5


1.1349345632955324e-06

# **1.3 Gradient Descent in Two Dimensions**

# **1.3.1**

In [ ]:
import numpy as np

from numpy import linalg as LA
#Gradient Descnet function for two dimentions
def gradient_descent_two_dimentions(partial_derivetive_x0, partial_derivetive_x1, tol, alpha, x0, iter):
  iter += 1 
  gradient_vector = np.array([(partial_derivetive_x0(x0)), (partial_derivetive_x1(x0))])
  x_k1 = x0 - np.dot(alpha, gradient_vector)
  gradient_vector_1 = np.array([(partial_derivetive_x0(x_k1)), (partial_derivetive_x1(x_k1))])
  if(abs(math.sqrt(pow(gradient_vector_1[0],2) + pow(gradient_vector_1[1],2))) < tol):
    print(iter)
    return x_k1
  nominator = np.dot(np.subtract(x_k1, x0), np.subtract(gradient_vector_1 , gradient_vector))
  denominator = pow(LA.norm(np.subtract(gradient_vector, gradient_vector_1)), 2)
  alpha = nominator / denominator 
  return  gradient_descent_two_dimentions(partial_derivetive_x0, partial_derivetive_x1, tol, alpha, x_k1, iter)

In [ ]:
def test_function(input):
  return input[0]**2 + input[0]*input[1] + input[1]**2

def partial_deriv0(input):
  return 2*input[0] + input[1]

def partial_deriv1(input):
  return input[0] + 2*input[1]

# **1.3.2**

In [ ]:
x0 = np.array([1,3])
gradient_descent_two_dimentions(partial_deriv0, partial_deriv1, 0.2, 0.5, x0, 0)

4


array([-0.00390571,  0.00405309])

In [ ]:
x0 = np.array([2,9])
gradient_descent_two_dimentions(partial_deriv0, partial_deriv1, 0.2, 0.5, x0, 0)

4


array([-0.0215838 ,  0.02262578])

In [ ]:
x0 = np.array([6,4])
gradient_descent_two_dimentions(partial_deriv0, partial_deriv1, 0.2, 0.5, x0, 0)

4


array([ 0.00065973, -0.00065002])

In [ ]:
x0 = np.array([10,14])
gradient_descent_two_dimentions(partial_deriv0, partial_deriv1, 0.2, 0.5, x0, 0)

4


array([-0.00090543,  0.00091668])

# **Optimization**

## **2.1 Epidemics Control**



In [ ]:
def daily_new_cases(I):
  return (0.9*(1-(I/17.3))-0.5)*I

In [ ]:
dynamic_gradient_descent(daily_new_cases, 6, 0.2, -0.5, 0)

3


7.578430431893377

# **2.2 Shape Optimization**

In [ ]:
# The material used would be 2000/(W) + 2*L*W + 2000/L
#L and W are in centimeters
# Vector (L,W)
def partial_L(input):
  return 2*input[1] - 2000/pow(input[0],2)

def partial_W(input):
  return 2*input[0] - 2000/pow(input[1],2)

In [ ]:
starting_point = np.array([1, 1])
gradient_descent_two_dimentions(partial_L, partial_W, 0.2, 0.05, starting_point, 0)

63


array([9.99692586, 9.99692586])

Therefore the optimized lengths are 10, 10, 10